### ISSUE TITLE
Permission to use your portfolio

### ISSUE THREAD

**Issue by patelrootul1** [planktoon1/anas-portfolio#1]
Hi @planktoon1,

I am Rootul, Reaching out to you for taking your permission to reuse your portfolio for my friend. She is recent graduate from BIM course and looking for possible ways to make her work visible, I happen to be Computer science engineer, wanting to help in making her work visible. 
I am impressed by the web app you guys made and kudos for the hard work. While there is no Open Source License for the project, I want to take all due permission from you guys to use your code and portfolio to manipulate it according to my requirement. 
Please do let me know if you grant the permission. 
Thank You!

**Comment by Frederik-OE** [comment]
Hi @patelrootul1, I've added a MIT license now so feel free to use the code for whatever purpose you want. Thanks for the compliment, happy it can be a help for you and your friend and thanks for asking
